apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: flask
  name: flask-app
  namespace: codefresh
spec:
  replicas: 3
  selector:
    matchLabels:
      run: flask
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: flask
    spec:
      containers:
      - image: davidfic/codefresh-test:master 
        name: flask-app
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---      
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    run: flask
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 5000
    protocol: TCP
  selector:
    run: flask


